# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='max_limit',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='usage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
