# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20181012_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
