# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_userprofile_pin'),
        ('Website', '0003_creditcard_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.CreditCard')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.UserProfile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Merchant')),
            ],
        ),
    ]
