# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_userprofile_pin'),
        ('Website', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Bank')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Merchant')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
