# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_userprofile_pin'),
        ('Website', '0005_auto_20181012_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Merchant')),
            ],
        ),
    ]
