# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_auto_20181012_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
