# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_auto_20181023_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
