# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govt_id', models.CharField(max_length=50)),
                ('gst_id', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Account')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('credit_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pan_number', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Account')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Bank')),
                ('credit_card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.CreditCard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
