# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 11:24
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_merchant_govt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='govt_id',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/abhay/Desktop/CreditCardSystem/private'), upload_to=b''),
        ),
    ]
