# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_merchant_govt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pin',
        ),
    ]
