# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_userprofile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='activation_code',
            field=models.CharField(default='merchant', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_code',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
