# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20181023_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credit_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
