# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 17:19
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20181026_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='govt_id',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/abhay/Desktop/Projects/CreditCardSystem/private'), upload_to=b''),
        ),
    ]
